---
title: "hierarchical"
author: "Leon Karreman"
date: "12/7/2021"
output: html_document
---

```{r setup, include=FALSE}
setwd('/home/leon/Documents/Data')
library(readr)
library(tidyverse)
library(lubridate)
library(tidyr)

dat1<-read_csv('Social_distancing_index_ST.csv',col_names=FALSE, col_select=-1)
setwd("/home/leon/Documents/Statts/speeches") 
prob<-read_csv('prob.csv')

```


## R Markdown
getting rid of other topic proportions
```{r}
prob<-prob[1:33,]
```
getting rid of states number column
```{r}
data<-dat1[,-1]
```
make columns correspond to states
```{r}

data<-t(data)
data<-as.data.frame(data)
#data<-data[2:602,1:51]



```
turn the first column in to a date object
```{r}
data$V1<-parse_date_time(data$V1,order='mdy')
```
make variables recognizable to r
```{r}

diffdata<-lapply(data[-1], as.numeric)
diffdata<-lapply(diffdata, diff)

```
```{r}
diffdata<-as.data.frame(diffdata)
```
```{r}
V1<-data[-1,1]
diffdata<-cbind(V1, diffdata)
```


plot random state's 
```{r cars}


plot(data$V2)
```
create empty matix
```{r}
matrix=as.data.frame(matrix(, nrow = 0, ncol = 52))
```
create object with speech dates
```{r}
speechdates=c('28-01-2020','12-09-2020','20-06-2020','18-08-2020','19-09-2020','10-09-2020','28-08-2020','14-01-2020','13-03-2020','08-08-2020','28-02-2020','10-02-2020','15-04-2020','03-09-2020','19-02-2020','30-01-2020','01-06-2020','01-09-2020','20-02-2020','07-09-2020','11-03-2020','13-09-2020','17-09-2020','04-07-2020','08-09-2020','02-03-2020','23-04-2020','22-09-2020','18-09-2020','13-04-2020','21-02-2020','21-09-2020','05-11-2020')


```


take social distancing index for the three days after every speech

```{r}
for (i in seq(1:33)) {
for (date in speechdates[i]) {
  new= diffdata[diffdata$V1 > dmy(date) & diffdata$V1 <= dmy(date)+days(3),]
  matrix=rbind(matrix, new)
  
} }

```

```{r}
realmatrix<-lapply(matrix[-1], as.numeric)
realmatrix<-as.data.frame(realmatrix)
```

```{r}
n <- 3;
realmatrix<-aggregate(realmatrix, list(rep(1:(nrow(matrix) %/% n + 1), each = n, len = nrow(matrix))), mean)[-1]

```
```{r}

realdf<-c(prob, realmatrix)
realdf<-as.data.frame(realdf)

```

```{r}
statenames<-dat1[["X2"]]
statenames <- statenames[-1]
#statenames<-as.character(statenames)
```

add statenames as columns 
```{r}
library(data.table)
statenames<-as.character(statenames)
setnames(realdf, old=c(colnames(realdf[-c(1,2,3,4,5,6)])),new=c(statenames))
```

```{r}
model<-lm(matrix$V47~prob$V3+prob$V1+prob$V2+prob$V5+prob$V4)
summary(model)
```
```{r}
newdata<-data.frame(realdf[1:6], stack(realdf[7:57]))
```


```{r}
library(lmerTest)
```



```{r}
fe<- lmer(formula=values ~ 1+V3+(1+V3|ind), data=newdata)
```

```{r}
summary(fe)
```
```{r}
coefs<-coef(fe)$ind


```

```{r}
coefs<-as.data.frame(coefs)
coefs
```
```{r}
library(blme)
(fe<- blmer(formula=values ~ V1+V3+(1||ind), data=newdata))
```

